# Generated by Django 5.1.4 on 2025-01-11 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_investor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('entrepreneur', 'Entrepreneur'), ('investor', 'Investisseur'), ('ONG-Association', 'ONG-Association'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('sector', models.CharField(choices=[('agriculture', 'Agriculture'), ('technology', 'Technology'), ('crafts', 'Crafts'), ('commerce', 'Commerce'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('tourism', 'Tourism'), ('manufacturing', 'Manufacturing'), ('services', 'Services')], max_length=50)),
                ('description', models.TextField()),
                ('specific_objectives', models.TextField()),
                ('target_audience', models.CharField(max_length=255)),
                ('estimated_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('financing_plan', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=20)),
                ('admin_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrepreneur_projects', to='main.entrepreneur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_card', "Carte Nationale d'Identité"), ('business_register', 'Registre de Commerce'), ('company_statutes', "Statuts de l'Entreprise"), ('tax_clearance', 'Attestation de Non Redevance Fiscale'), ('permits', 'Permis et Licences'), ('intellectual_property', 'Propriété Intellectuelle'), ('photos', 'Photos'), ('feasibility_study', 'Étude de Faisabilité')], max_length=50)),
                ('file', models.FileField(upload_to='project_documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_required', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.project')),
            ],
            options={
                'unique_together': {('project', 'document_type')},
            },
        ),
    ]
