# Generated by Django 5.1.4 on 2025-01-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_projectphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='document_type',
            field=models.CharField(choices=[('id_card', "Carte Nationale d'Identité"), ('business_register', 'Registre de Commerce'), ('company_statutes', "Statuts de l'Entreprise"), ('tax_clearance', 'Attestation de Non Redevance Fiscale'), ('permits', 'Permis et Licences'), ('intellectual_property', 'Propriété Intellectuelle'), ('photos', 'photo'), ('feasibility_study', 'Étude de Faisabilité'), ('project_image', 'Image du Projet')], max_length=50),
        ),
        migrations.DeleteModel(
            name='ProjectPhoto',
        ),
    ]
