# Generated by Django 5.1.4 on 2025-01-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_projectdocument_document_type'),
    ]

    operations = [

    ]
