# Generated by Django 5.1.4 on 2025-01-14 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_helprequest_financialrequest_technicalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('refused', 'Refused')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('investment_type', models.CharField(max_length=50)),
                ('payment_schedule', models.CharField(max_length=50)),
                ('expected_return', models.TextField()),
                ('timeline', models.TextField()),
                ('additional_terms', models.TextField(blank=True, null=True)),
                ('help_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_proposals', to='main.helprequest')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_proposals', to='main.investor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnicalProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('refused', 'Refused')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expertise', models.TextField()),
                ('experience_level', models.CharField(max_length=50)),
                ('availability', models.TextField()),
                ('support_duration', models.CharField(max_length=100)),
                ('support_type', models.CharField(max_length=50)),
                ('proposed_approach', models.TextField()),
                ('additional_resources', models.TextField(blank=True, null=True)),
                ('expected_outcomes', models.TextField()),
                ('help_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_proposals', to='main.helprequest')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_proposals', to='main.investor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
